version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eurosong
    ports:
      - "3306:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: ghcr.io/moadt18/examen-2024-backend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      db_host: database
      db_user: root
      db_pass: root
      db_name: eurosong
      db_port: 3306
      cors_origin: http://localhost:8080
      HOST: 0.0.0.0
      PORT: 3000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build: ./frontend
    image: ghcr.io/moad-touhafi/examen-2024-frontend:latest
    ports:
      - "8080:80"
    environment:
      VUE_APP_BACKEND_API_URL: http://backend:3000
    depends_on:
      - backend
    networks:
      - app_network
  mysql-client:
    image: mysql:8.0
    command: ["mysql", "-h", "database", "-u", "root", "-proot", "eurosong"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eurosong
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
networks:
  app_network:
    driver: bridge