# pr-checks.yml (example)
name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/backend/package-lock.json', '**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Re-install dependencies
      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm install

      - name: Test Backend
        run: |
          cd backend
          npm test

      - name: Test Frontend
        run: |
          cd frontend
          npm test

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Re-install dependencies
      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm install

      - name: Lint Backend
        run: |
          cd backend
          npm run lint

      - name: Lint Frontend
        run: |
          cd frontend
          npm run lint
